task:
  name: Build
  persistent_worker: {}
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
  env_script:
    - env
  clone_script:
    - repo init --depth=1 -u https://github.com/PixelPlusUI/manifest -b eleven
  sync_script:
    - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
  device_script:
    - git clone https://github.com/P-Salik/android_device_realme_RMX1941 device/realme/RMX1941
    - git clone https://github.com/P-Salik/android_vendor_realme_RMX1941 vendor/realme/RMX1941
    - cd external/selinux
    - wget https://github.com/PixelExperience/external_selinux/commit/9d6ebe89430ffe0aeeb156f572b2a810f9dc98cc.patch
    - patch -p1 < *.patch
    - cd ../..
    - cd frameworks/base
    - wget https://github.com/PixelExperience/frameworks_base/commit/37f5a323245b0fd6269752742a2eb7aa3cae24a7.patch
    - patch -p1 < *.patch
    - cd ../..
    - cd frameworks/opt/net/wifi
    - wget https://github.com/PixelExperience/frameworks_opt_net_wifi/commit/3bd2c14fbda9c079a4dc39ff4601ba54da589609.patch
    - patch -p1 < *.patch
    - cd ../../../..
    - cd frameworks/opt/net/wifi
    - wget https://github.com/PixelExperience/frameworks_opt_net_wifi/commit/3bd2c14fbda9c079a4dc39ff4601ba54da589609.patch
    - patch -p1 < *.patch
    - cd ../../../..
  build_script:
    - . build/envsetup.sh
    - lunch aosp_RMX1941-user
    - mka bacon -j8
  ccache_stats_script:
    - ccache -s
  upload_script: |
    up() {
      curl --upload-file $1 https://transfer.sh/$(basename $1); echo
      # 14 days, 10 GB limit
    }

    up out/target/product/mido/*.zip
