task:
  name: Build
  persistent_worker: {}
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
  env_script:
    - env
  rom_sync:
    - repo init -u https://github.com/PixelExperience/manifest -b eleven
    - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
  device:
    - git clone https://github.com/P-Salik/android_device_realme_RMX1941 device/rea>
    - git clone https://github.com/P-Salik/android_vendor_realme_RMX1941 vendor/rea>
    - cd /external/selinux git fetch https://github.com/PixelExperience/external_se>
    - cd /frameworks/base git fetch https://github.com/PixelExperience/frameworks_b>
    - cd /frameworks/opt/net/wifi git fetch https://github.com/PixelExperience/fram>
    - cd /frameworks/opt/net/ims git fetch https://github.com/PixelExperience/frame>
    - cd ../../../../
  build_script:
    - source build/envsetup.sh
    - lunch aosp_RMX1941-user
    - mka bacon -j8
  ccache_stats_script:
    - ccache -s
  upload_script: |
    up() {
      curl --upload-file $1 https://transfer.sh/$(basename $1); echo
      # 14 days, 10 GB limit
    }
    up out/target/product/RMX1941/*.zip
