task:
    name: Sync test
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 4
      memory: 8G
    sync_script:
      - bash sync_rom.sh
    build_script:
      - bash build_rom.sh
    upload_script:
      - bash upload_rom.sh
#start build
