env: 
    CIRRUS_CLONE_DEPTH: 1 
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: "ENCRYPTED[aad75c1906c0011ae7d72e7c62993aadb28fd22900718372aefb3e6f91b16e79d18dea026613257a4cea98ff4ba4a2b5]"

task:
  name: Build
  persistent_worker: {}
  timeout_in: 2h
  container:
    image: apon77/aosp:latest
    cpu: 4
    memory: 8G
  download_ccache_script:
    - bash download_ccache
  sync_script:
    - rm -rf .repo || true
    - bash sync_rom.sh
  build_script:
    - bash build_rom.sh
  ccache_stats_script:
    - ccache -s
  upload_script:
    - bash upload_rom.sh
  upload_ccache_script:
    - bash upload_ccache
